# Generated by Django 2.0.2 on 2018-02-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='modificado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Modificado em'),
        ),
    ]
