# Generated by Django 2.0.2 on 2018-02-20 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_noticias_modificado_em'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='noticias',
            table='noticias',
        ),
    ]
