# Generated by Django 2.0.2 on 2018-02-20 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180220_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('descricao', models.TextField(max_length=255, verbose_name='Descrição')),
            ],
            options={
                'db_table': 'categoria',
            },
        ),
        migrations.RenameModel(
            old_name='Noticias',
            new_name='Noticia',
        ),
        migrations.AlterModelTable(
            name='noticia',
            table='core_noticias',
        ),
    ]
